// Authentication path
export const CoreUrl = {
  API_PATH: 'api/v1',
  AUTH: 'auth',
  AUTHENTICATE: 'authenticate',
  LOGIN: 'login',
  NO_ACCESS: 'no-access',
  WAITING_ACCESS: 'waiting-access',
  LOGIN_SSO: 'sso',
  LOGOUT: 'logout',
  REGISTER: 'register',
  REQUEST_ACCESS: 'register-internal-user',
  REFRESH: 'validate-token',
  ME: 'associate',
  EXTERNAL: 'external',
  REFRESH_TOKEN:'refresh-token',

  // Error path
  ERROR_403: '403',
  ERROR_404: '404',
  ERROR_500: '500',
  NO_PERMISSION: 'no-permisison',

  // Addition path
  DASHBOARD: 'dashboard',
  USER_INF: 'user-information',
  ASSOCIATE_INF: 'associate-info',
  ManageRequest: 'manage-request',
  // API Data
  API: 'api',
  PROJECTS: 'projects',
  USER_MANAGEMENT: 'user-management',
  V_MODEL: 'vmodel',
  REPORT: 'report',
  PersonalInformation: 'personal-information',
  HomePage: 'home-page',
  DEPARTMENT_PROJECTS: 'projects',
  Learning: 'learning',
  GROUP: 'groups',
  PROJECT: 'project',
  ASSOCIATE: 'associate',
  FILTER: 'filter',
  SKILL: 'skill',
  ROLE: 'project-role',
  GB: 'gb',
  PHASE: 'phase',
  DROPDOWN: 'dropdown',
  COURSE: 'course',
  EXPORT: 'export',
  SYSTEM: 'system',
  TASK: 'tasks',
  SUPPLY: 'demand-supply',
  TRAVEL_PLAN: 'travel-plan',
  COMPETENCE_DEVELOPMENT: 'competence-development',
  EET_OVERVIEW:"overview",
  PROJECT_LIST:"project-list",
  PERSONAL_INFO:"personal-info",
  RELEASE_NOTE:"release-note",
  OVERVIEW:"overview",
  ORG_CHART:"org-chart",
  HELP:"help"
};
