/*
 * Copyright (c) 2022, Robert Bosch GmbH and its subsidiaries.
 * This program and the accompanying materials are made available under
 * the terms of the Bosch Internal Open Source License v4
 * which accompanies this distribution, and is available at
 * http://bios.intranet.bosch.com/bioslv4.txt
 */

package com.bosch.eet.skill.management.elasticsearch.repo;

/**
 *
 * @author DUP5HC
 */

public final class ElasticCommon {

    public static final String PERSONAL_BODY = "{\r\n"
    		+ "    \"aliases\": {},\r\n"
    		+ "    \"mappings\": {\r\n"
    		+ "        \"properties\": {\r\n"
    		+ "            \"id\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"personalId\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"personalCode\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"displayName\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"level\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"team\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"experience \": {\r\n"
    		+ "                \"type\": \"integer\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"department\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"gbUnit\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"location\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skills\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skillGroups\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            }\r\n"
    		+ "        }\r\n"
    		+ "    },\r\n"
    		+ "    \"settings\": {\r\n"
    		+ "        \"index\": {\r\n"
    		+ "            \"number_of_shards\": \"5\",\r\n"
    		+ "            \"number_of_replicas\": \"1\"\r\n"
    		+ "        },\r\n"
    		+ "        \"default_pipeline\": \"personalindex\"\r\n"
    		+ "    }\r\n"
    		+ "}";
    
    public static final String PROJECT_BODY = "{\r\n"
    		+ "    \"aliases\": {},\r\n"
    		+ "    \"mappings\": {\r\n"
    		+ "        \"properties\": {\r\n"
    		+ "            \"id\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"projectId\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"projetName\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"projecType\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"projectManager\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"customerGB \": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"gbUnit \": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"team\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"status\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"startDate\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"endDate\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"technologyUsed\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"description\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
			+ "            \"objective\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"topProject\": {\r\n"
    		+ "                \"type\": \"boolean\"\r\n"
    		+ "            },\r\n"
			+ "            \"highlight\": {\r\n"
			+ "                \"type\": \"text\",\r\n"
			+ "                \"fields\": {\r\n"
			+ "                    \"keyword\": {\r\n"
			+ "                        \"type\": \"keyword\",\r\n"
			+ "                        \"ignore_above\": 256\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            },\r\n"
			+ "            \"scopeId\": {\r\n"
			+ "                \"type\": \"text\",\r\n"
			+ "                \"fields\": {\r\n"
			+ "                    \"keyword\": {\r\n"
			+ "                        \"type\": \"keyword\",\r\n"
			+ "                        \"ignore_above\": 256\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            },\r\n"
			+ "            \"scopeName\": {\r\n"
			+ "                \"type\": \"text\",\r\n"
			+ "                \"fields\": {\r\n"
			+ "                    \"keyword\": {\r\n"
			+ "                        \"type\": \"keyword\",\r\n"
			+ "                        \"ignore_above\": 256\r\n"
			+ "                    }\r\n"
			+ "                }\r\n"
			+ "            },\r\n"
    		+ "            \"teamSize\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            }\r\n"
    		+ "        }\r\n"
    		+ "    },\r\n"
    		+ "    \"settings\": {\r\n"
    		+ "        \"index\": {\r\n"
    		+ "            \"number_of_shards\": \"5\",\r\n"
    		+ "            \"number_of_replicas\": \"1\"\r\n"
    		+ "        },\r\n"
    		+ "        \"default_pipeline\": \"personalindex\"\r\n"
    		+ "    }\r\n"
    		+ "}";
    public static final String SKILL_BODY = "{\r\n"
    		+ "    \"aliases\": {},\r\n"
    		+ "    \"mappings\": {\r\n"
    		+ "        \"properties\": {\r\n"
    		+ "            \"id\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skillId\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skillName\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skillGroup\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"skillType\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"isRequired\": {\r\n"
    		+ "                \"type\": \"boolean\"\r\n"
    		+ "            },\r\n"
    		+ "            \"isMandatory\": {\r\n"
    		+ "                \"type\": \"boolean\"\r\n"
    		+ "            },\r\n"
    		+ "            \"skillLevels\": {\r\n"
    		+ "                \"type\": \"nested\",\r\n"
    		+ "                \"include_in_parent\": true,\r\n"
    		+ "                \"properties\": {\r\n"
    		+ "                    \"id\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"name\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"skillId\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"level\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"description \": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            }\r\n"
    		+ "        }\r\n"
    		+ "    },\r\n"
    		+ "    \"settings\": {\r\n"
    		+ "        \"index\": {\r\n"
    		+ "            \"number_of_shards\": \"5\",\r\n"
    		+ "            \"number_of_replicas\": \"1\"\r\n"
    		+ "        },\r\n"
    		+ "        \"default_pipeline\": \"personalindex\"\r\n"
    		+ "    }\r\n"
    		+ "}";
    
    
    public static final String COURSE_BODY = "{\r\n"
    		+ "    \"aliases\": {},\r\n"
    		+ "    \"mappings\": {\r\n"
    		+ "        \"properties\": {\r\n"
    		+ "            \"id\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"courseId\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"courseType\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"courseName\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"trainer\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"startDate\": {\r\n"
    		+ "                \"type\": \"date\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"effort\": {\r\n"
    		+ "                \"type\": \"integer\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"targetAudience\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"status\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            }\r\n"
    		+ "        }\r\n"
    		+ "    },\r\n"
    		+ "    \"settings\": {\r\n"
    		+ "        \"index\": {\r\n"
    		+ "            \"number_of_shards\": \"5\",\r\n"
    		+ "            \"number_of_replicas\": \"1\"\r\n"
    		+ "        },\r\n"
    		+ "        \"default_pipeline\": \"personalindex\"\r\n"
    		+ "    }\r\n"
    		+ "}";

    public static final String CUSTOMER_GB_BODY="{\r\n"
    		+ "    \"aliases\": {},\r\n"
    		+ "    \"mappings\": {\r\n"
    		+ "        \"properties\": {\r\n"
    		+ "            \"id\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"name\": {\r\n"
    		+ "                \"type\": \"text\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"numOfProject\": {\r\n"
    		+ "                \"type\": \"integer\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"numOfHC\": {\r\n"
    		+ "                \"type\": \"integer\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"numberOfTool\": {\r\n"
    		+ "                \"type\": \"integer\",\r\n"
    		+ "                \"fields\": {\r\n"
    		+ "                    \"keyword\": {\r\n"
    		+ "                        \"type\": \"keyword\",\r\n"
    		+ "                        \"ignore_above\": 256\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"projects\": {\r\n"
    		+ "                \"type\": \"nested\",\r\n"
    		+ "                \"include_in_parent\": true,\r\n"
    		+ "                \"properties\": {\r\n"
    		+ "                    \"id\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"name\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            },\r\n"
    		+ "            \"tags\": {\r\n"
    		+ "                \"type\": \"nested\",\r\n"
    		+ "                \"include_in_parent\": true,\r\n"
    		+ "                \"properties\": {\r\n"
    		+ "                    \"name\": {\r\n"
    		+ "                        \"type\": \"text\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    },\r\n"
    		+ "                    \"numberOfTag\": {\r\n"
    		+ "                        \"type\": \"integer\",\r\n"
    		+ "                        \"fields\": {\r\n"
    		+ "                            \"keyword\": {\r\n"
    		+ "                                \"type\": \"keyword\",\r\n"
    		+ "                                \"ignore_above\": 256\r\n"
    		+ "                            }\r\n"
    		+ "                        }\r\n"
    		+ "                    }\r\n"
    		+ "                }\r\n"
    		+ "            }\r\n"
    		+ "        }\r\n"
    		+ "    },\r\n"
    		+ "    \"settings\": {\r\n"
    		+ "        \"index\": {\r\n"
    		+ "            \"number_of_shards\": \"5\",\r\n"
    		+ "            \"number_of_replicas\": \"1\"\r\n"
    		+ "        },\r\n"
    		+ "        \"default_pipeline\": \"personalindex\"\r\n"
    		+ "    }\r\n"
    		+ "}";

    public static final String SEARCH_QUERY = "/query";
    public static final String QUERY = "query";
    public static final String HITS = "hits";
    public static final String TOOK = "took";
    public static final String TOTAL_HITS = "total";
    public static final String VALUE = "value";
    public static final String CONTENT_ACCEPT = "Accept";
    public static final String APP_TYPE = "application/json";
    public static final String CONTENT_TYPE = "Content-type";
    public static final Integer TO_MS = 1000;
    public static final String ENCODING_UTF8 = "UTF-8";

}
